name: alioth-S-Update

on: workflow_dispatch

jobs:
  build-alioth-Android-S:
    runs-on: self-hosted
    steps:
      - name: Update alioth 
        run: |
          source /home/lurenjia534/Pixel-alioth/build/envsetup.sh
          lunch aosp_alioth-userdebug
