name: alioth-S-Update

on: workflow_dispatch

jobs:
  build-alioth-Android-S:
    runs-on: self-hosted
    steps:
      - name: Update repo sync
        run: |
          cd /home/lurenjia534/Pixel-alioth
          repo sync
      - name: Update alioth 
        run: |
          source /home/lurenjia534/alioth/build/envsetup.sh
          lunch aosp_alioth-userdebug
      - name: build clean
        run: |
          cd /home/lurenjia534/alioth
          make clean
