name: Redmi-K40

on: workflow_dispatch

jobs:
  build-alioth-Android-S:
    runs-on: self-hosted
    steps:
      - name: device info
        run: |
          source /home/lurenjia534/Pixel-alioth/build/envsetup.sh
          lunch aosp_alioth-userdebug
      - name: Build alioth Android 12 
        run: |
          cd /home/lurenjia534/Pixel-alioth
          croot
          mka bacon -j$(nproc --all)
