name: Redmi-K40

on: workflow_dispatch

jobs:
  build-alioth-Android-S:
    runs-on: self-hosted
    steps:
      - name: make build Android12
        run: |
          cd /home/lurenjia534/Pixel-alioth
          croot
          mka bacon -j$(nproc --all)
